version: "3"

services:
  # MySQL 5.7.x
  db:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      TERM: linux
    volumes:
      - ./storage/database:/var/lib/mysql
      - ./storage/logs:/var/log/mysql
    networks:
      - internal
    dns:
      - 8.8.8.8
      - 8.8.4.4

  # Redis 3.2.x
  redis:
    restart: always
    image: redis:3.2-alpine
    environment:
      TERM: linux
    volumes:
      - ./storage/redis:/data
    networks:
      - internal
    dns:
      - 8.8.8.8
      - 8.8.4.4

  # PHP-FPM 7.0.x
  php7:
    restart: always
    image: rikkeisoft/docker-for-php:latest
    environment:
      DEBUG: 1
      TERM: linux
    volumes:
      - ./resources/php7.0-fpm/php.ini:/etc/php.ini:ro
      - ./resources/php7.0-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ./storage/logs:/var/log/php-fpm
      - .:/app
    networks:
      - external
      - internal
    dns:
      - 8.8.8.8
      - 8.8.4.4

  # Nginx 1.10.x
  web:
    restart: always
    image: nginx:stable-alpine
    ports:
      - "5555:80"
    volumes:
      - ./resources/nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
      - ./storage/logs:/var/log/nginx
      - .:/app
    networks:
      - external
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  external:
    driver: bridge
  internal:
    driver: bridge
